/**
 * KOMIK.ID - Database & Initial Data
 * Menyediakan data awal lengkap untuk Manhwa, Manhua, dan Manga
 * Memenuhi seluruh judul yang diminta pengguna beserta genre lengkap & sinopsis
 */

const ALL_GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Coming of Age",
  "Cultivation",
  "Dark Fantasy",
  "Drama",
  "Fantasy",
  "Historical",
  "Horror",
  "Isekai",
  "Magic",
  "Martial Arts",
  "Mystery",
  "Murim",
  "Ninja",
  "Psychological",
  "Rebirth",
  "Reincarnation",
  "Revenge",
  "Romance",
  "School Life",
  "Sci-Fi",
  "Shoujo",
  "Shounen",
  "Slice of Life",
  "Sports",
  "Steampunk",
  "Supernatural",
  "Superpower",
  "Survival"
];

function generateChapters(totalCount) {
  const chapters = [];
  for (let i = totalCount; i >= 1; i--) {
    chapters.push({
      number: i,
      title: `Chapter ${i}`,
      releaseDate: '',
      isNew: false
    });
  }
  return chapters;
}

function availableChapter(number) {
  return [{ number, title: `Chapter ${number}`, releaseDate: '', isNew: false }];
}
const INITIAL_COMICS = [
  // ==========================================
  // MANHWA (KOREA)
  // ==========================================
  {
    id: "love-revolution",
    title: "Love Revolution",
    altTitle: "Yeonaehyeokmyeong",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.6,
    votes: "14.2k",
    status: "Tamat",
    author: "232",
    artist: "232",
    releaseYear: "2013",
    totalChapters: 432,
    latestChapter: 432,
    isTrending: true,
    isTopPick: false,
    badgeText: "POPULER",
    synopsis: "Gong Joo-young jatuh cinta pada pandangan pertama dengan Wang Ja-rim, siswi SMA berhati dingin dan pendiam. Melalui tekad pantang menyerah, aksi lucu menggemaskan, serta dukungan para sahabatnya, Joo-young berusaha meluluhkan hati Ja-rim. Sebuah komedi romantis remaja yang penuh warna dan sangat realistis menggambarkan kehidupan anak SMA.",
    genres: ["Romance", "Comedy", "School Life", "Drama", "Slice of Life", "Shoujo"],
    coverImage: "assets/covers/Love_Revolution.jpg",
    bannerImage: "assets/banners/lorev.jpg",
    chapters: availableChapter(432)
  },
  {
    id: "lookism",
    title: "Lookism",
    altTitle: "Park Tae-jun",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.8,
    votes: "48.5k",
    status: "Ongoing",
    author: "Park Tae-jun (PTJ)",
    artist: "PTJ Company",
    releaseYear: "2014",
    totalChapters: 626,
    latestChapter: 626,
    isTrending: true,
    isTopPick: true,
    badgeText: "HOT",
    synopsis: "Park Hyung-suk, seorang siswa yang menjadi korban bullying ekstrem karena fisiknya yang gemuk dan penampilannya, mengalami fenomena supernatural yang mengubah hidupnya: ia terbangun dengan tubuh kedua yang sangat tampan, tinggi, dan memiliki kemampuan atletik tingkat dewa! Saat tubuh yang satu tidur, tubuh yang lain aktif. Namun di balik kegemilangan dunia barunya, terdapat perang antar kru empat divisi yang mematikan di jalanan Seoul.",
    genres: ["Drama", "Action", "School Life", "Comedy", "Romance"],
    coverImage: "assets/covers/lookism.jpg",
    bannerImage: "assets/banners/lookism banner.jpg",
    chapters: availableChapter(626)
  },
  {
    id: "wind-breaker",
    title: "Wind Breaker",
    altTitle: "Street Racing",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.7,
    votes: "32.1k",
    status: "Ongoing",
    author: "Jo Yong-seok",
    artist: "Jo Yong-seok",
    releaseYear: "2013",
    totalChapters: 555,
    latestChapter: 555,
    isTrending: true,
    isTopPick: false,
    badgeText: "HOT",
    synopsis: "Jay (Jo Ja-hyun) adalah ketua OSIS SMA Taeyang yang pintar dan pendiam, yang didorong oleh keluarganya untuk hanya fokus pada akademik. Namun pelarian sesungguhnya adalah mengendarai sepeda fixed-gear (fixie). Ketika ia bertemu kru sepeda Hummingbird, Jay terseret ke dalam turnamen balap jalanan ekstrem bernama 'League of Street'. Bersama teman-temannya, ia menguji batas kecepatan, adrenalin, dan persahabatan.",
    genres: ["Sports", "Drama", "Action", "School Life", "Comedy"],
    coverImage: "assets/covers/wb cover.jpg",
    bannerImage: "assets/banners/wb banner.jpg",
    chapters: availableChapter(555)
  },
  {
    id: "eleceed",
    title: "Eleceed",
    altTitle: "Awakened & Cats",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.9,
    votes: "41.9k",
    status: "Ongoing",
    author: "Son Je-ho",
    artist: "Zhena",
    releaseYear: "2018",
    totalChapters: 401,
    latestChapter: 401,
    isTrending: true,
    isTopPick: true,
    badgeText: "BARU",
    synopsis: "Seo Ji-woo adalah pemuda baik hati yang menyembunyikan kekuatan kecepatan kilatnya dan sangat mencintai kucing jalanan. Suatu hari ia menyelamatkan seekor kucing oranye gemuk yang terluka parah. Tanpa diduga, kucing itu adalah wujud persembunyian Kayden Break — awakened legendaris pemilik petir terkuat di dunia! Di bawah bimbingan sang 'kucing petir', Jiwoo mulai mengarungi bahaya dunia pertarungan para pengguna kekuatan supranatural.",
    genres: ["Action", "Fantasy", "Comedy", "Supernatural", "Superpower"],
    coverImage: "assets/covers/eleceed cover.jpg",
    bannerImage: "assets/banners/eleceed banner.jpg",
    chapters: availableChapter(401)
  },
  {
    id: "orv",
    title: "Omniscient Reader's Viewpoint",
    altTitle: "ORV",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.9,
    votes: "65.4k",
    status: "Ongoing",
    author: "sing N song",
    artist: "Sleepy-C (Redice Studio)",
    releaseYear: "2020",
    totalChapters: 217,
    latestChapter: 217,
    isTrending: true,
    isTopPick: true,
    badgeText: "HOT",
    synopsis: "'Hanya ada satu orang yang membaca novel ini sampai tuntas.' Kim Dok-ja adalah seorang pegawai kantoran biasa yang kegemarannya membaca novel web 'Tiga Cara Bertahan Hidup di Dunia Hancur' selama 10 tahun. Saat chapter terakhir novel itu selesai dibaca, dunia nyata seketika runtuh dan monster dari skenario novel muncul membumihanguskan Seoul. Sebagai satu-satunya orang yang tahu seluruh rahasia cerita, Dok-ja mengambil alih takdir dunia.",
    genres: ["Action", "Fantasy", "Adventure", "Apocalyptic", "Drama", "Mystery"],
    coverImage: "assets/covers/orv cover.jpg",
    bannerImage: "assets/banners/orv banner.jpg",
    chapters: availableChapter(217)
  },
  {
    id: "tbate",
    title: "The Beginning After the End",
    altTitle: "TBATE (Arthur Leywin)",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.8,
    votes: "39.7k",
    status: "Ongoing",
    author: "TurtleMe",
    artist: "Fuyuki23",
    releaseYear: "2018",
    totalChapters: 171,
    latestChapter: 171,
    isTrending: true,
    isTopPick: false,
    badgeText: "POPULER",
    synopsis: "Raja Grey memiliki status militer, kekayaan, dan kemuliaan tertinggi yang tak tertandingi di dunianya. Namun kesepian selalu membayanginya. Setelah kematian misteriusnya, ia terlahir kembali ke benua magis Dicathen sebagai Arthur Leywin. Membawa kenangan dan wawasan bela diri kehidupan sebelumnya, Arthur bertekad melindungi keluarga dan orang-orang yang dicintainya dari bayang-bayang perang benua yang mengerikan.",
    genres: ["Action", "Adventure", "Fantasy", "Drama", "Reincarnation", "Magic"],
    coverImage: "assets/covers/tbate.jpg",
    bannerImage: "assets/banners/tbate banner.jpg",
    chapters: availableChapter(171)
  },
  {
    id: "solo-leveling-ragnarok",
    title: "Solo Leveling: Ragnarok",
    altTitle: "Solo Leveling: Ragnarok",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.8,
    votes: "18.3k",
    status: "Ongoing",
    author: "Daul / Chugong",
    artist: "Redice Studio",
    releaseYear: "2024",
    totalChapters: 68,
    latestChapter: 68,
    isTrending: true,
    isTopPick: true,
    badgeText: "BARU",
    synopsis: "Dunia kembali terancam setelah gerbang-gerbang misterius terbuka kembali dari kehampaan dimensi. Sung Su-ho, putra tunggal dari Sung Jin-woo sang Shadow Monarch, harus membangkitkan garis keturunan kegelapan di dalam dirinya untuk menangkis invasi para dewa luar demi melindungi umat manusia.",
    genres: ["Action", "Fantasy", "Adventure", "Drama", "Supernatural"],
    coverImage: "assets/covers/solo leveling ragnarok.jpg",
    bannerImage: "assets/banners/solev banner.jpg",
    chapters: [{
      number: 68,
      title: "Chapter 68",
      pages: [
        "assets/comics/solo-leveling-ragnarok/chapter 68/00-a9a68b.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/01-d90c0e.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/02-a4b9cd.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/03-585776.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/04-fd81aa.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/05-fcdd7d.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/06-98eeff.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/07-a166be.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/08-4f7c57.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/09-420bed.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/10-1da170.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/11-45ba94.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/12-88e6da.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/13-d248cb.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/14-785168.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/15-3f3686.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/16-07d341.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/17-589b97.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/18-fa5802.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/19-13e094.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/20-410b6c.jpg",
        "assets/comics/solo-leveling-ragnarok/chapter 68/21-cd36eb.jpg"
      ]
    }]
  },
  {
    id: "nano-machine",
    title: "Nano Machine",
    altTitle: "Nano Machine",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.5,
    votes: "27.8k",
    status: "Ongoing",
    author: "Hanjoong Wolya",
    artist: "Geumgangbulgoe",
    releaseYear: "2020",
    totalChapters: 331,
    latestChapter: 331,
    isTrending: true,
    isTopPick: false,
    badgeText: "HOT",
    synopsis: "Dilahirkan sebagai pangeran rendahan di Klan Iblis dan selalu terancam dibunuh, nasib Cheon Yeo-woon berubah drastis setelah seorang keturunannya dari masa depan tiba-tiba menyuntikkan mesin nano berteknologi tinggi ke dalam tubuhnya. Dengan integrasi teknologi masa depan dan seni bela diri Murim, Yeo-woon menapaki jalan untuk menjadi Penguasa Surgawi Klan Iblis.",
    genres: ["Action", "Fantasy", "Martial Arts", "Murim", "Sci-Fi", "Reincarnation"],
    coverImage: "assets/covers/nano cover.jpg",
    bannerImage: "assets/banners/nano banner.jpg",
    chapters: availableChapter(331)
  },
  {
    id: "the-greatest-estate-developer",
    title: "The Greatest Estate Developer",
    altTitle: "The Greatest Estate Developer",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.9,
    votes: "52.7k",
    status: "Ongoing",
    author: "BK_Moon",
    artist: "Kim Hyunsoo",
    releaseYear: "2021",
    totalChapters: 152,
    latestChapter: 152,
    isTrending: true,
    isTopPick: false,
    badgeText: "POPULER",
    synopsis: "Kim Suho, seorang mahasiswa teknik sipil Korea, bereinkarnasi ke dalam dunia novel fantasi sebagai Lloyd Frontera — seorang bangsawan pemalas yang membuat keluarganya terlilit hutang raksasa. Berbekal ilmu teknik sipil modern, sistem pembangunan magis, dan ekspresi wajah paling licik sekaligus jenaka, Lloyd mulai merombak total tanah wilayahnya!",
    genres: ["Comedy", "Fantasy", "Adventure", "Isekai", "Reincarnation", "Drama"],
    coverImage: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=500&auto=format&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80",
    chapters: []
  },
  {
    id: "swordmasters-youngest-son",
    title: "Swordmaster's Youngest Son",
    altTitle: "Swordmaster's Youngest Son",
    type: "manhwa",
    countryCode: "KR",
    countryName: "Korea",
    rating: 9.7,
    votes: "24.6k",
    status: "Ongoing",
    author: "AZI",
    artist: "COIN",
    releaseYear: "2022",
    totalChapters: 112,
    latestChapter: 112,
    isTrending: false,
    isTopPick: false,
    badgeText: "BARU",
    synopsis: "Jin Runcandel adalah putra bungsu dari klan ahli pedang terhebat di dunia, klan Runcandel. Karena dianggap tidak berbakat, ia diusir dan mati sia-sia. Namun dewa bayangan Solderlet memberinya kesempatan kedua untuk hidup kembali ke masa kecilnya. Kini ia menguasai ilmu pedang, sihir, sekaligus sihir dewa bayangan!",
    genres: ["Action", "Fantasy", "Adventure", "Drama", "Reincarnation", "Magic"],
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    chapters: []
  },

  // ==========================================
  // MANGA (JEPANG)
  // ==========================================
  {
    id: "one-piece",
    title: "One Piece",
    altTitle: "Eiichiro Oda",
    type: "manga",
    countryCode: "JP",
    countryName: "Jepang",
    rating: 9.9,
    votes: "75.2k",
    status: "Ongoing",
    author: "Eiichiro Oda",
    artist: "Eiichiro Oda",
    releaseYear: "1997",
    totalChapters: 1194,
    latestChapter: 1194,
    isTrending: true,
    isTopPick: true,
    badgeText: "LEGEND",
    synopsis: "Gol D. Roger, Raja Bajak Laut yang dieksekusi, memicu Era Kejayaan Bajak Laut dengan kata-kata terakhirnya tentang harta karun rahasia 'One Piece'. Bertahun-tahun kemudian, Monkey D. Luffy, pemuda berkekuatan karet buah iblis Gomu Gomu, merekrut kru setia Bajak Laut Topi Jerami dan mengarungi ganasnya Grand Line demi impian menjadi Raja Bajak Laut berikutnya.",
    genres: ["Action", "Adventure", "Fantasy", "Comedy", "Drama", "Superpower"],
    coverImage: "assets/covers/one piece.jpg",
    bannerImage: "assets/banners/onepiece.jpg",
    chapters: availableChapter(1194)
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    altTitle: "Gege Akutami",
    type: "manga",
    countryCode: "JP",
    countryName: "Jepang",
    rating: 9.7,
    votes: "52.8k",
    status: "Tamat",
    author: "Gege Akutami",
    artist: "Gege Akutami",
    releaseYear: "2018",
    totalChapters: 236,
    latestChapter: 236,
    isTrending: true,
    isTopPick: false,
    badgeText: "HOT",
    synopsis: "Yuji Itadori adalah siswa SMA dengan kekuatan fisik luar biasa yang secara tidak sengaja menelan jari terkutuk Ryomen Sukuna, Raja Kutukan legendaris, untuk menyelamatkan temannya. Bergabung ke SMK Jujutsu Tokyo di bawah asuhan penyihir terkuat Satoru Gojo, Yuji harus mengumpulkan seluruh sisa jari kutukan sebelum dirinya dieksekusi demi kedamaian dunia.",
    genres: ["Action", "Supernatural", "Dark Fantasy", "Horror", "School Life"],
    coverImage: "assets/covers/jujutsu.jpg",
    bannerImage: "assets/banners/jjk.jpg",
    chapters: availableChapter(236)
  },
  {
    id: "chainsaw-man",
    title: "Chainsaw Man",
    altTitle: "Denji & Pochita",
    type: "manga",
    countryCode: "JP",
    countryName: "Jepang",
    rating: 9.6,
    votes: "44.9k",
    status: "Ongoing",
    author: "Tatsuki Fujimoto",
    artist: "Tatsuki Fujimoto",
    releaseYear: "2018",
    totalChapters: 277,
    latestChapter: 277,
    isTrending: true,
    isTopPick: false,
    badgeText: "BARU",
    synopsis: "Denji adalah pemuda miskin yang terjerat hutang yakuza dan bertahan hidup sebagai pemburu iblis bersama anjing iblis gergajinya, Pochita. Setelah dikhianati dan dibunuh, Pochita menyatu dengan jantung Denji, mengubahnya menjadi 'Chainsaw Man' manusia hibrida dengan gergaji mesin yang meraung dari tangan dan kepalanya.",
    genres: ["Action", "Dark Fantasy", "Horror", "Supernatural", "Comedy", "Drama"],
    coverImage: "assets/covers/csm.jpg",
    bannerImage: "assets/banners/csm detail komik.jpg",
    chapters: availableChapter(277)
  },

  // ==========================================
  // MANHUA (CHINA)
  // ==========================================
  {
    id: "lotm",
    title: "Lord of the Mysteries",
    altTitle: "Klein Moretti",
    type: "manhua",
    countryCode: "CN",
    countryName: "China",
    rating: 9.9,
    votes: "58.0k",
    status: "Ongoing",
    author: "Cuttlefish That Loves Diving",
    artist: "Wawayu Animation",
    releaseYear: "2020",
    totalChapters: 15,
    latestChapter: 15,
    isTrending: true,
    isTopPick: true,
    badgeText: "HOT",
    synopsis: "Zhou Mingrui terbangun di dunia alternatif era Victoria yang dipenuhi mesin uap, cerobong asap pabrik, dan ritual terlarang mistis sebagai Klein Moretti. Mengonsumsi ramuan misterius 'Beyonder', Klein merintis jalan kepalsuan dan kebenaran, membentuk Tarot Club legendaris di atas kabut kelabu, dan menyingkap rahasia para dewa kuno.",
    genres: ["Fantasy", "Mystery", "Supernatural", "Steampunk", "Adventure", "Drama"],
    coverImage: "assets/covers/lotm cover.jpg",
    bannerImage: "assets/banners/lotm banner.jpg",
    chapters: availableChapter(15)
  },
  {
    id: "magic-emperor",
    title: "Magic Emperor",
    altTitle: "Demonic Emperor / Zhuo Fan",
    type: "manhua",
    countryCode: "CN",
    countryName: "China",
    rating: 9.8,
    votes: "49.1k",
    status: "Ongoing",
    author: "Wuer Manhua",
    artist: "Nightingale",
    releaseYear: "2019",
    totalChapters: 915,
    latestChapter: 915,
    isTrending: true,
    isTopPick: false,
    badgeText: "HOT",
    synopsis: "Zhuo Yifan adalah Kaisar Iblis legendaris yang menguasai Kitab Rahasia Sembilan Ketenangan. Karena dikhianati murid kepercayaannya, ia tewas dan jiwanya bereinkarnasi ke tubuh seorang pelayan klan Luo bernama Zhuo Fan. Terikat oleh kutukan hati pemilik tubuh terdahulu, Zhuo Fan bertekad membawa klan Luo yang miskin menuju puncak kekuasaan dan membalas dendam dengan kelicikan iblisnya.",
    genres: ["Action", "Fantasy", "Martial Arts", "Reincarnation", "Historical", "Cultivation"],
    coverImage: "assets/covers/magiccover.jpg",
    bannerImage: "assets/banners/magicemperor.jpg",
    chapters: availableChapter(915)
  },
  {
    id: "apotheosis",
    title: "Apotheosis - Ascension to Godhood",
    altTitle: "Ascension to Godhood",
    type: "manhua",
    countryCode: "CN",
    countryName: "China",
    rating: 8.9,
    votes: "33.5k",
    status: "Ongoing",
    author: "Ranzai Studio",
    artist: "Ranzai Studio",
    releaseYear: "2015",
    totalChapters: 1140,
    latestChapter: 1140,
    isTrending: false,
    isTopPick: false,
    badgeText: "BARU",
    synopsis: "Luo Zheng, mantan tuan muda klan Luo yang jatuh menjadi budak samsara, menemukan sebuah buku kuno misterius yang memungkinkannya mengolah tubuhnya menjadi senjata ilahi tak terkalahkan. Demi menyelamatkan adiknya Luo Yan, ia bangkit menembus ribuan sekte dan menjadi dewa sejati pencipta alam semesta.",
    genres: ["Action", "Fantasy", "Martial Arts", "Adventure", "Cultivation"],
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1200&auto=format&fit=crop&q=80",
    chapters: []
  },
  {
    id: "tales-of-demons-and-gods",
    title: "Tales of Demons and Gods",
    altTitle: "Tales of Demons and Gods",
    type: "manhua",
    countryCode: "CN",
    countryName: "China",
    rating: 9.7,
    votes: "43.2k",
    status: "Ongoing",
    author: "Mad Snail",
    artist: "Jiang Ruotai",
    releaseYear: "2015",
    totalChapters: 468,
    latestChapter: 468,
    isTrending: false,
    isTopPick: false,
    badgeText: "POPULER",
    synopsis: "Nie Li, Spiritualis Iblis terkuat yang terbunuh dalam pertempuran terakhir melawan Kaisar Sage, terlahir kembali ke masa ketika ia masih berusia 13 tahun berkat Kitab Roh Iblis Ruang dan Waktu. Berbekal memori masa depan, Nie Li berlatih teknik dewa dan bertekad menyelamatkan Kota Glory serta melindungi wanita yang dicintainya.",
    genres: ["Action", "Fantasy", "Adventure", "Romance", "Reincarnation", "Cultivation"],
    coverImage: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=500&auto=format&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=1200&auto=format&fit=crop&q=80",
    chapters: []
  }
].filter(comic => ![
  'swordmasters-youngest-son',
  'the-greatest-estate-developer',
  'apotheosis',
  'tales-of-demons-and-gods'
].includes(comic.id));
